### ISSUE TITLE
cabal index doesn't provide necessary info

### ISSUE THREAD

**Issue by Freed-Wu** [brandonchinn178/toml-reader#29]
According to <https://github.com/berberman/arch-hs/issues/84>, cabal index doesn't provide necessary info.

**Comment by brandonchinn178** [comment]
I'm not sure what this means. I think what the other person meant is that Cabal doesnt provide this info in general, so you have to run a separate command to expose the info to arch-hs. I think you have to call `gen-setup` before running the command that's failing. It's not a bug in toml-reader, you have to do this for any package that doesnt provide Setup.hs (which is an optional file)

**Comment by Freed-Wu** [comment]
@felixonmars so It's also not the bug of tmol-reader? Is it possible to `gen-setup` automatically in `PKGBUILD` generated by `arch-hs`.

**Comment by felixonmars** [comment]
@Freed-Wu It's not a bug of any individual packages not providing Setup.hs. It's also not possible for arch-hs to know whether `gen-setup` is needed because the Cabal index doesn't carry information about it (and downloading the tarball to analyze is way more expensive). So I don't really see how we could improve the situation :(
